version: '3.8'

services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: rest
    volumes:
      - prisma_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@localhost:5432/mydb?schema=public
      JWT_SECRET: change-me
      NODE_ENV: development
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app:cached
    command: sh -c "npx prisma migrate deploy && npm run start:dev"

volumes:
  prisma_data:
